### PR TITLE
Use only one instance for every tab

### PR DESCRIPTION
**Pull request by marcofugaro**
Some work in progress for issue #21 

I tried putting all the logic in the `decorateTerms` instead of the single `decorateTerm`, but couldn't find a way to access the term instance. So I moved all the logic in a separated class and reference its instance in both `decorateTerms` and `decorateTerm`.

`decorateTerms` is used to listen for the `componentWillUnmount` hook.

`decorateTerm` is used to initialize the application, switch the canvasTextures and move the canvas element in the dom.

What do you think @slammayjammay?

**Note**: it won't work in local for now because it's I just moved the code and wrote some pseudocode.

### CODE REVIEW

**Comment by slammayjammay** [comment]
This is a good start BUT panes need to be supported as well, #22. Assuming each pane has one renderer, it's possible that somebody can have for example two tabs with one containing 2 panes and the other containing 4 and you gotta swap/destroy/add them all correctly.

**Comment by slammayjammay** [comment]
Or it might be possible to somehow combine all panes into just one renderer, in which case you might not need to worry about multiple instance of THREE, but I think that might be pretty involved and I don't know if I can do it.

**Comment by marcofugaro** [comment]
Right, panes, totally forgot those.

To show multiple canvases at the same time, I think the best solution would be using the `1 renderer -> multiple scenes` approach [like int this example](https://threejs.org/examples/?q=elements#webgl_multiple_elements). And implementation-wise, I think we should use that same approach also with multiple tabs, it should be performant and it's easier to implement rather than moving the canvas around in the dom (especially when there are multiple panes).

I wrote some pseudo-code that might work using this approach, but I can't figure out how to detect when a term is not visible anymore. For example, let's say a pane is still animating even if it's not in focus (`isTermActive === false`). Then the user switches tab, how do we stop the animation loop of that pane since now it's not anymore visible? And how do we restart it after the user goes back but that pane is still not in focus?

The only solution I could think of involves using `MutationObserver` and checking the css classes in the dom, do you have a better idea?

**Comment by slammayjammay** [comment]
Hmmm, looking at the source for that example, the renderer still renders once for each scene. So this would save the need for multiple renderers but the number of renders for each tab/pane would remain unchanged from current. My understanding of three+postprocessing is that the number of renders per frame is the bottleneck for performance; having multiple renderers in the background is of course not ideal but as long as they're inactive they shouldn't have any impact on frame rate. Of course there's a good chance I'm wrong on this :). It's probably still worth looking into but it'd be a pretty sizable refactor.

Anyway regarding active terms, as far as I know there isn't an API to get all visible terminal sessions, just the "active" one. But you can deduce them by making use of `window.store.getState()`, it lists all "termGroups" including the "activeRootGroup" under which you can find visible "termGroups". It seems like "termGroup" refers to both a terminal session and also an abstract grouping of terminal sessions. i.e. opening 3 vertical panes shows 4 "termGroups", but if one of them is horizontal 5 "termGroups" show up. shrug

From there I think you can make use of one of the `exports.decorate...` functions. I played around with `decorateHyper` and thought that might be a good place to house logic for multiple panes/tabs. `componentWillReceiveProps` will probably let you know when terms become active/inactive, as opposed to `MutationObserver`s.

**Comment by marcofugaro** [comment]
You misunderstood me, the objective is to pause the `requestAnimationFrame` and so not calling `renderer.render(scene, camera)` for non-visible terms :) (like it works now but with 1 renderer since it's more performant). I am trying to find a way to achieve this while still supporting panes, the objective is to render simultaneously to all the panes of the active tab, and don't render the tab which is not visible.

I'll try using `window.store.getState()` and keeping tracks of the ids, that's promising.
However using `componentWillReceiveProps` will not work with the rendering also to the other visible panes in the tab, since non-active panes are already inactive, and when the user changes tab, they trigger no `componentWillReceiveProps`. So there is no way to trigger a `cancelAnimationLoop`.

**Comment by slammayjammay** [comment]
> using `componentWillReceiveProps` will not work

Depends on the component you use. The `decorateTerms` or `decorateTerm` components won't always fire when a user switches between tabs/panes, but `decorateHyper` will. You can make use of that to get the active/inactive tabs and then do whatever.

**Comment by marcofugaro** [comment]
Thank you! I'll try that

**Comment by slammayjammay** [comment]
Hey @marcofugaro, FYI this seems to work for getting visible tabs/panes, you might be able to borrow some of it.

https://github.com/slammayjammay/hyper-postprocessing/blob/panes/src/index.js#L100-L135

**Comment by slammayjammay** [comment]
Fixed in [v3](https://github.com/slammayjammay/hyper-postprocessing/releases/tag/v3.0.0)

**Pull request closed without merging**
